//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexivoSIH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCatalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mCatalogo()
        {
            this.Catalogo11 = new HashSet<Catalogo>();
        }
    
        public int mcatalogo_id { get; set; }
        public string catalogo { get; set; }
        public bool estado { get; set; }
    
        public virtual Catalogo Catalogo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogo> Catalogo11 { get; set; }
    }
}
